"""init

Revision ID: 9b1db450833b
Revises: 
Create Date: 2021-11-17 17:57:34.907406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b1db450833b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hbtracker_telegram_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('user_nickname', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index(op.f('ix_hbtracker_telegram_user_user_nickname'), 'hbtracker_telegram_user', ['user_nickname'], unique=True)
    op.create_table('hbtracker_habits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_telegram_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_telegram_id'], ['hbtracker_telegram_user.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hbtracker_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['hbtracker_habits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hbtracker_events')
    op.drop_table('hbtracker_habits')
    op.drop_index(op.f('ix_hbtracker_telegram_user_user_nickname'), table_name='hbtracker_telegram_user')
    op.drop_table('hbtracker_telegram_user')
    # ### end Alembic commands ###
