"""add duration to events

Revision ID: c5fb467c5ec9
Revises: 9b1db450833b
Create Date: 2021-11-19 14:09:22.185362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5fb467c5ec9'
down_revision = '9b1db450833b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hbtracker_events', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('hbtracker_events', sa.Column('is_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hbtracker_events', 'is_completed')
    op.drop_column('hbtracker_events', 'duration')
    # ### end Alembic commands ###
